### ISSUE TITLE
Link Shawee na foto

### ISSUE THREAD

**Issue by LeoMoreiraS** [dev-house-community/Hackathon-01#2]
não sei como faz se faz uma issue, nem se faria isso aqui mas acho que seria bacana quando clicar na foto da shawee ali redirecionar pra página deles.

**Comment by jakeliny** [comment]
Fez certinho!! no readme se usa markdown, depois de vc fazer a alteração abre um PR e linkar com essa issue 

Fica aqui o guide do markdown: https://guides.github.com/features/mastering-markdown/

**Comment by LeoMoreiraS** [comment]
![hackathon dev house](https://user-images.githubusercontent.com/17316392/116326974-20164800-a79c-11eb-889d-064161f21dfe.png)

## Cronograma
- 12/07 as 19h: Live #01 esquenta hackathon - tema em breve
- 13/07 as 19h: Live #02 esquenta hackathon - tema em breve
- 14/07 as 19h: Live #03 esquenta hackathon - tema em breve
- 15/07 as 19h: Live #04 esquenta hackathon - tema em breve
- 16/07 as 17h: Live de abertura

### 
- 16/07 as 18h: ***Inicio oficial do hackathon***
- 16/07 as 18h: Inicio das mentorias e plantões de duvidas
- 18/07 as 23h59h: ***Limite para envio do projeto***


## Apoiadores
<div align="center">
    <a href="https://shawee.io/pt/">
        <img src="https://user-images.githubusercontent.com/17316392/116294997-fa267e80-a76e-11eb-82ac-2326290dffc0.png" alt="Shawee" width=300/>
    </a>
</div>

---
Evento idealizado e planejado com ❤️ pela Dev House Community, faça parte da comunidade no [discord](https://discord.gg/hUjdjevDCz)

**Comment by jakeliny** [comment]
PR aprovado!!
